"use client";

import type { GenerativeImageStates } from "generative-components";
import { useState } from "react";
import Link from "next/link";
import {
  GenerativeImage,
  GenerativeImageSkeleton,
  generativeImageStates,
} from "generative-components";
import { FaGithub } from "react-icons/fa";

import { StateToggle } from "../../components/state-toggle";

export default function Home() {
  const [controlledState, setControlledState] = useState<
    GenerativeImageStates | undefined
  >("loading");

  return (
    <main className="flex min-h-screen flex-col items-center justify-start bg-[#101010] p-8">
      <div className="mt-8">
        {controlledState === "loading" && <GenerativeImageSkeleton />}
        {(controlledState === "default" || controlledState === "hover") && (
          <GenerativeImage
            src="https://source.unsplash.com/random/600x600?travel"
            alt="Image Caption"
            model="dall-e-3"
            controlledState={controlledState}
          />
        )}
      </div>
      <div className="mx-auto my-24 flex w-[650px] max-w-full flex-col justify-start">
        <p className="mb-2 text-sm font-light tracking-wide text-white">
          Generative Image
        </p>
        <p className="text-sm font-light tracking-wide text-[#888]">
          Displays image content generated by language models.
        </p>
        <hr className="my-16 border-[#333] border-opacity-50" />
        <div className="flex flex-row flex-wrap justify-between gap-16 text-white">
          <StateToggle
            states={generativeImageStates as readonly GenerativeImageStates[]}
            activeState={controlledState ?? "loading"}
            onStateChange={setControlledState}
          />

          <div className="flex w-full flex-row-reverse items-center justify-end gap-4 tracking-wide md:w-fit md:flex-row">
            <span className="text-xs font-light">
              Built by{" "}
              <Link href={"https://twitter.com/danielsims"}>danielsims</Link>
            </span>
            <Link href={"https://github.com/danielsims/generative-ui"}>
              <FaGithub className="fill-white text-white" size={24} />
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
